import { Database } from "bun:sqlite";
import { rebuildAutoLinks } from "./mcp/engine/linker";
const db = new Database(process.env.PDB!);
const rel = () => db.query(`SELECT relationship, COUNT(*) c FROM links GROUP BY relationship ORDER BY c DESC`).all() as any[];
console.log("BEFORE:", rel().map(r=>`${r.relationship}=${r.c}`).join(" "));
const s = performance.now();
const r = rebuildAutoLinks(db);
console.log(`rebuild: ${((performance.now()-s)/1000).toFixed(1)}s  notes=${r.notes}  related_to ${r.linksBefore} -> ${r.linksAfter}`);
console.log("AFTER: ", rel().map(x=>`${x.relationship}=${x.c}`).join(" "));
const m = db.query(`SELECT MAX(c) m FROM (SELECT from_note_id, COUNT(*) c FROM links WHERE relationship='related_to' GROUP BY from_note_id)`).get() as any;
console.log("max related_to out-degree:", m.m);
